apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubevirt

resources:
  - namespace.yaml
  # The operator and CR are installed via Tiltfile local_resource
  # because KubeVirt CRDs must be installed before the CR can be applied

commonLabels:
  app.kubernetes.io/name: kubevirt
  app.kubernetes.io/part-of: development-platform
