apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: macos-disk
  namespace: macos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
