---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
spec:
  accessModes:
  - {{ .Values.pvc.mssqldataaccessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.mssqldbsize }}
  {{- if .Values.pvc.StorageClass }}
  storageClassName: {{ .Values.pvc.StorageClass | quote }}
  {{- end }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-userdb
spec:
  accessModes:
  - {{ .Values.pvc.userdbaccessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.userdbsize }}
  {{- if .Values.pvc.StorageClass }}
  storageClassName: {{ .Values.pvc.StorageClass | quote }}
  {{- end }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-log
spec:
  accessModes:
  - {{ .Values.pvc.userlogaccessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.userlogsize }}
  {{- if .Values.pvc.StorageClass }}
  storageClassName: {{ .Values.pvc.StorageClass | quote }}
  {{- end }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-temp
spec:
  accessModes:
  - {{ .Values.pvc.tempdbaccessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.tempsize }}
  {{- if .Values.pvc.StorageClass }}
  storageClassName: {{ .Values.pvc.StorageClass | quote }}
  {{- end }}
