---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: wordpress
type: Opaque
stringData:
  wordpress-password: wp-dev-pass
  mysql-root-password: mysql-root-dev
  mysql-password: wp-db-pass
