---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: wordpress
type: Opaque
stringData:
  wordpress-password: wordpress
  mysql-root-password: rootpassword
  mysql-password: wordpress
