apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: app-batches
  namespace: app
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/CICD/items/Batches"