apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: storage-connect-string
  namespace: keda
spec:
  itemPath: "vaults/CICD/items/Azure Blob - Documents"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: storage-connect-string-sftp-cust
  namespace: keda
spec:
  itemPath: "vaults/CICD/items/Azure Blob - SFTP Customer"