app:
  title: Dev Portal
  baseUrl: http://localhost:3000

organization:
  name: SysTechs

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, Domain, Group, API, Resource, Location, Template]
  locations:
    - type: file
      target: ../../examples/entities.yaml
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters: []

permission:
  enabled: true

# Tilt integration (custom plugin)
tilt:
  baseUrl: http://localhost:10350

# Grafana integration
grafana:
  domain: https://grafana.localhost
  unifiedAlerting: true

# Argo CD integration
argocd:
  baseUrl: https://argocd.localhost
  appLocatorMethods:
    - type: 'config'
      instances:
        - name: main
          url: https://argocd.localhost

# Proxy for Grafana API
proxy:
  endpoints:
    '/grafana/api':
      target: https://grafana.localhost
      headers:
        Authorization: 'Bearer ${GRAFANA_TOKEN}'
      changeOrigin: true
      secure: false
