apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dapr-dashboard
  namespace: dapr-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dapr.localhost`)
      kind: Rule
      services:
        - name: dapr-dashboard
          port: 8080
  tls: {}
