apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eyeos
  namespace: eyeos
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
  - host: eyeos.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eyeos
            port:
              number: 6080
