apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterhub
  namespace: jupyterhub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jupyterhub
  namespace: jupyterhub
rules:
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaims"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyterhub
  namespace: jupyterhub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jupyterhub
subjects:
- kind: ServiceAccount
  name: jupyterhub
  namespace: jupyterhub
