---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    externalURL: http://harbor.localhost
    exposureType: ingress
    adminPassword: "P@ssw0rd" #Don't do this in production
    trivy:
      enabled: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor
  namespace: harbor
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`harbor.localhost`) || Host(`www.harbor.localhost`) && PathPrefix(`/`)
      priority: 1
      services:
        - name: harbor-portal
          namespace: harbor
          port: 80
    - kind: Rule
      match: Host(`harbor.localhost`) && PathPrefix(`/c/`) || Host(`www.harbor.localhost`) && PathPrefix(`/c/`)
      priority: 10
      services:
        - kind: Service
          name: harbor-core
          namespace: harbor
          port: 80
    - kind: Rule
      match: Host(`harbor.localhost`) && PathPrefix(`/api/`) || Host(`www.harbor.localhost`) && PathPrefix(`/api/`)
      priority: 10
      services:
        - kind: Service
          name: harbor-core
          namespace: harbor
          port: 80
    - kind: Rule
      match: Host(`harbor.localhost`) && PathPrefix(`/service/`) || Host(`www.harbor.localhost`) && PathPrefix(`/service/`)
      priority: 10
      services:
        - kind: Service
          name: harbor-core
          namespace: harbor
          port: 80
    - kind: Rule
      match: Host(`harbor.localhost`) && PathPrefix(`/v2/`) || Host(`www.harbor.localhost`) && PathPrefix(`/v2/`)
      priority: 10
      services:
        - kind: Service
          name: harbor-core
          namespace: harbor
          port: 80
    - kind: Rule
      match: Host(`harbor.localhost`) && PathPrefix(`/chartrepo/`) || Host(`www.harbor.localhost`) && PathPrefix(`/chartrepo/`)
      priority: 10
      services:
        - kind: Service
          name: harbor-core
          namespace: harbor
          port: 80