apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eyeos-disk
  namespace: eyeos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: ""
