---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: rabbitmq
type: Opaque
stringData:
  rabbitmq-username: "rmq_user"
  rabbitmq-password: "rmq-dev-password"
  rabbitmq-erlang-cookie: "rmq-erlang-cookie-dev"
