{%- if values.createIngress and values.port %}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.name }}
    app.kubernetes.io/name: ${{ values.name }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: ${{ values.name }}.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${{ values.name }}
                port:
                  number: ${{ values.port }}
  tls:
    - hosts:
        - ${{ values.name }}.localhost
      secretName: wildcard-localhost-tls
{%- endif %}
