apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repo.yaml
  - helm-release.yaml
  - namespace.yaml
  - secrets/app-batches.yaml
  - secrets/storage-connect-string.yaml
  - secrets/service-bus-connect-string.yaml