import type { TechRadarApi, TechRadarLoaderResponse } from '@backstage/plugin-tech-radar';

const techRadarData: TechRadarLoaderResponse = {
  quadrants: [
    { id: 'infrastructure', name: 'Infrastructure' },
    { id: 'data-messaging', name: 'Data & Messaging' },
    { id: 'observability', name: 'Observability' },
    { id: 'cicd-security', name: 'CI/CD & Security' },
  ],
  rings: [
    { id: 'adopt', name: 'Adopt', color: '#5ba300' },
    { id: 'trial', name: 'Trial', color: '#009eb0' },
    { id: 'assess', name: 'Assess', color: '#c7ba00' },
    { id: 'hold', name: 'Hold', color: '#e09b96' },
  ],
  entries: [
    // --- Infrastructure ---
    {
      key: 'kubernetes',
      id: 'kubernetes',
      title: 'Kubernetes',
      quadrant: 'infrastructure',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Core orchestration platform via Docker Desktop', moved: 0 }],
      description: 'Container orchestration platform powering all workloads',
      url: 'https://kubernetes.io',
    },
    {
      key: 'traefik',
      id: 'traefik',
      title: 'Traefik',
      quadrant: 'infrastructure',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Primary ingress controller', moved: 0 }],
      description: 'Cloud-native ingress controller and reverse proxy',
      url: 'https://traefik.io',
    },
    {
      key: 'crossplane',
      id: 'crossplane',
      title: 'Crossplane',
      quadrant: 'infrastructure',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'trial', description: 'Cloud-native infrastructure as code', moved: 0 }],
      description: 'Control plane framework for building cloud platforms',
      url: 'https://crossplane.io',
    },
    {
      key: 'cert-manager',
      id: 'cert-manager',
      title: 'cert-manager',
      quadrant: 'infrastructure',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Manages TLS certificates', moved: 0 }],
      description: 'Cloud-native certificate management for Kubernetes',
      url: 'https://cert-manager.io',
    },
    {
      key: 'flux',
      id: 'flux',
      title: 'Flux CD',
      quadrant: 'infrastructure',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'GitOps toolkit for cluster reconciliation', moved: 0 }],
      description: 'GitOps toolkit for Kubernetes',
      url: 'https://fluxcd.io',
    },
    {
      key: 'dapr',
      id: 'dapr',
      title: 'Dapr',
      quadrant: 'infrastructure',
      timeline: [{ date: new Date('2024-06-01'), ringId: 'trial', description: 'Distributed application runtime', moved: 0 }],
      description: 'Portable, event-driven runtime for building microservices',
      url: 'https://dapr.io',
    },
    {
      key: 'backstage',
      id: 'backstage',
      title: 'Backstage',
      quadrant: 'infrastructure',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Developer portal and service catalog', moved: 0 }],
      description: 'Open platform for building developer portals',
      url: 'https://backstage.io',
    },
    {
      key: 'tilt',
      id: 'tilt',
      title: 'Tilt',
      quadrant: 'infrastructure',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Local dev orchestrator for k8s', moved: 0 }],
      description: 'Multi-service dev environment orchestrator',
      url: 'https://tilt.dev',
    },
    {
      key: 'kubevirt',
      id: 'kubevirt',
      title: 'KubeVirt',
      quadrant: 'infrastructure',
      timeline: [{ date: new Date('2024-06-01'), ringId: 'assess', description: 'VM workloads on Kubernetes', moved: 0 }],
      description: 'Run virtual machines alongside containers on Kubernetes',
      url: 'https://kubevirt.io',
    },
    // --- Data & Messaging ---
    {
      key: 'postgresql',
      id: 'postgresql',
      title: 'PostgreSQL',
      quadrant: 'data-messaging',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Primary relational database', moved: 0 }],
      description: 'Advanced open-source relational database',
      url: 'https://www.postgresql.org',
    },
    {
      key: 'redis',
      id: 'redis',
      title: 'Redis',
      quadrant: 'data-messaging',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Caching and event streaming', moved: 0 }],
      description: 'In-memory data store for caching, messaging, and streaming',
      url: 'https://redis.io',
    },
    {
      key: 'rabbitmq',
      id: 'rabbitmq',
      title: 'RabbitMQ',
      quadrant: 'data-messaging',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Message broker for async communication', moved: 0 }],
      description: 'Open-source message broker with AMQP support',
      url: 'https://www.rabbitmq.com',
    },
    {
      key: 'nats',
      id: 'nats',
      title: 'NATS',
      quadrant: 'data-messaging',
      timeline: [{ date: new Date('2024-06-01'), ringId: 'trial', description: 'Lightweight cloud-native messaging', moved: 0 }],
      description: 'Cloud-native messaging system for microservices',
      url: 'https://nats.io',
    },
    {
      key: 'qdrant',
      id: 'qdrant',
      title: 'Qdrant',
      quadrant: 'data-messaging',
      timeline: [{ date: new Date('2024-06-01'), ringId: 'trial', description: 'Vector search for AI/ML', moved: 0 }],
      description: 'Vector similarity search engine for AI applications',
      url: 'https://qdrant.tech',
    },
    {
      key: 'mongodb',
      id: 'mongodb',
      title: 'MongoDB',
      quadrant: 'data-messaging',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Document database', moved: 0 }],
      description: 'General-purpose document database',
      url: 'https://www.mongodb.com',
    },
    {
      key: 'mssql',
      id: 'mssql',
      title: 'SQL Server',
      quadrant: 'data-messaging',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Enterprise relational database', moved: 0 }],
      description: 'Microsoft SQL Server for enterprise workloads',
      url: 'https://www.microsoft.com/sql-server',
    },
    {
      key: 'localstack',
      id: 'localstack',
      title: 'LocalStack',
      quadrant: 'data-messaging',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Local AWS service emulation', moved: 0 }],
      description: 'Local AWS cloud stack emulator for development',
      url: 'https://localstack.cloud',
    },
    {
      key: 'azurite',
      id: 'azurite',
      title: 'Azurite',
      quadrant: 'data-messaging',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Local Azure Storage emulation', moved: 0 }],
      description: 'Azure Storage emulator for local development',
      url: 'https://github.com/Azure/Azurite',
    },
    // --- Observability ---
    {
      key: 'prometheus',
      id: 'prometheus',
      title: 'Prometheus',
      quadrant: 'observability',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Core metrics and monitoring', moved: 0 }],
      description: 'Open-source monitoring and alerting toolkit',
      url: 'https://prometheus.io',
    },
    {
      key: 'grafana',
      id: 'grafana',
      title: 'Grafana',
      quadrant: 'observability',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Visualization and dashboarding', moved: 0 }],
      description: 'Observability and data visualization platform',
      url: 'https://grafana.com',
    },
    {
      key: 'loki',
      id: 'loki',
      title: 'Loki',
      quadrant: 'observability',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Log aggregation backend', moved: 0 }],
      description: 'Horizontally-scalable log aggregation system',
      url: 'https://grafana.com/oss/loki/',
    },
    {
      key: 'tempo',
      id: 'tempo',
      title: 'Tempo',
      quadrant: 'observability',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Distributed tracing backend', moved: 0 }],
      description: 'Cost-effective distributed tracing backend',
      url: 'https://grafana.com/oss/tempo/',
    },
    {
      key: 'otel-collector',
      id: 'otel-collector',
      title: 'OpenTelemetry Collector',
      quadrant: 'observability',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Unified telemetry pipeline', moved: 0 }],
      description: 'Vendor-agnostic telemetry data collection and export',
      url: 'https://opentelemetry.io',
    },
    {
      key: 'thanos',
      id: 'thanos',
      title: 'Thanos',
      quadrant: 'observability',
      timeline: [{ date: new Date('2024-06-01'), ringId: 'trial', description: 'Long-term Prometheus storage', moved: 0 }],
      description: 'Highly available Prometheus setup with long-term storage',
      url: 'https://thanos.io',
    },
    {
      key: 'opencost',
      id: 'opencost',
      title: 'OpenCost',
      quadrant: 'observability',
      timeline: [{ date: new Date('2024-06-01'), ringId: 'trial', description: 'Kubernetes cost monitoring', moved: 0 }],
      description: 'Real-time cost monitoring for Kubernetes workloads',
      url: 'https://www.opencost.io',
    },
    {
      key: 'langfuse',
      id: 'langfuse',
      title: 'Langfuse',
      quadrant: 'observability',
      timeline: [{ date: new Date('2024-06-01'), ringId: 'assess', description: 'LLM observability and tracing', moved: 0 }],
      description: 'Open-source LLM engineering platform for tracing and evaluation',
      url: 'https://langfuse.com',
    },
    // --- CI/CD & Security ---
    {
      key: 'argocd',
      id: 'argocd',
      title: 'Argo CD',
      quadrant: 'cicd-security',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'GitOps continuous delivery', moved: 0 }],
      description: 'Declarative GitOps CD for Kubernetes',
      url: 'https://argo-cd.readthedocs.io',
    },
    {
      key: 'argo-workflows',
      id: 'argo-workflows',
      title: 'Argo Workflows',
      quadrant: 'cicd-security',
      timeline: [{ date: new Date('2024-06-01'), ringId: 'trial', description: 'Workflow engine for Kubernetes', moved: 0 }],
      description: 'Kubernetes-native workflow engine for CI/CD pipelines',
      url: 'https://argoproj.github.io/workflows/',
    },
    {
      key: 'jenkins',
      id: 'jenkins',
      title: 'Jenkins',
      quadrant: 'cicd-security',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'hold', description: 'Legacy CI server, migrating to Argo', moved: 0 }],
      description: 'Open-source automation server for CI/CD',
      url: 'https://www.jenkins.io',
    },
    {
      key: 'harbor',
      id: 'harbor',
      title: 'Harbor',
      quadrant: 'cicd-security',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Container registry with security scanning', moved: 0 }],
      description: 'Cloud-native container registry with vulnerability scanning',
      url: 'https://goharbor.io',
    },
    {
      key: 'falco',
      id: 'falco',
      title: 'Falco',
      quadrant: 'cicd-security',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Runtime security and threat detection', moved: 0 }],
      description: 'Cloud-native runtime security project',
      url: 'https://falco.org',
    },
    {
      key: 'trivy',
      id: 'trivy',
      title: 'Trivy',
      quadrant: 'cicd-security',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Vulnerability scanning for containers', moved: 0 }],
      description: 'Comprehensive security scanner for vulnerabilities and misconfigurations',
      url: 'https://trivy.dev',
    },
    {
      key: 'kyverno',
      id: 'kyverno',
      title: 'Kyverno',
      quadrant: 'cicd-security',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Kubernetes-native policy management', moved: 0 }],
      description: 'Kubernetes-native policy management engine',
      url: 'https://kyverno.io',
    },
    {
      key: 'wazuh',
      id: 'wazuh',
      title: 'Wazuh',
      quadrant: 'cicd-security',
      timeline: [{ date: new Date('2024-06-01'), ringId: 'trial', description: 'SIEM and compliance monitoring', moved: 0 }],
      description: 'Open-source SIEM for threat detection and compliance',
      url: 'https://wazuh.com',
    },
    {
      key: 'keycloak',
      id: 'keycloak',
      title: 'Keycloak',
      quadrant: 'cicd-security',
      timeline: [{ date: new Date('2024-01-01'), ringId: 'adopt', description: 'Identity and access management', moved: 0 }],
      description: 'Open-source identity and access management',
      url: 'https://www.keycloak.org',
    },
    {
      key: 'velero',
      id: 'velero',
      title: 'Velero',
      quadrant: 'cicd-security',
      timeline: [{ date: new Date('2024-06-01'), ringId: 'trial', description: 'Backup and disaster recovery', moved: 0 }],
      description: 'Backup and migrate Kubernetes resources and persistent volumes',
      url: 'https://velero.io',
    },
    {
      key: 'ollama',
      id: 'ollama',
      title: 'Ollama',
      quadrant: 'data-messaging',
      timeline: [{ date: new Date('2024-06-01'), ringId: 'trial', description: 'Local LLM inference', moved: 0 }],
      description: 'Run large language models locally',
      url: 'https://ollama.com',
    },
  ],
};

export default techRadarData;

export class CustomTechRadarApi implements TechRadarApi {
  async load(_id: string | undefined): Promise<TechRadarLoaderResponse> {
    return techRadarData;
  }
}
