apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 1m
  chart:
    spec:
      chart: kyverno
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    rbac:
      create: true
      serviceAccount:
        create: true
        name: kyverno