apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - configmaps.yaml
  - pvcs.yaml
  - indexer.yaml
  - manager.yaml
  - dashboard.yaml
  - ingress.yaml
  - filebeat-daemonset.yaml
  - dashboard-provisioner.yaml
configMapGenerator:
  - name: wazuh-dashboard-provisioner
    namespace: wazuh
    files:
      - create-dashboards.sh
generatorOptions:
  disableNameSuffixHash: true
