---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-indexer-data
  namespace: wazuh
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-manager-data
  namespace: wazuh
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
