---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  # Docker Desktop's kubelet certificates have the same problem as kind's.
  - target:
      kind: HelmRelease
      name: metrics-server
    patch: |
      - op: add
        path: /spec/values/args
        value:
          - --kubelet-insecure-tls
          - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP
