apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argo-workflows
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - argo
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-workflows-controller
  endpoints:
    - port: metrics
      interval: 30s
