apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: harbor-exporter
  namespace: harbor
  labels:
    app: harbor-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: harbor
  namespaceSelector:
    matchNames:
      - harbor
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
