apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  selector:
    matchLabels:
      app: loki
  namespaceSelector:
    matchNames:
      - logging
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
