apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qdrant
  namespace: qdrant
  labels:
    app: qdrant
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: qdrant
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
